{"uuid":"daeff89f-da78-45da-b803-6e294cd9d5df","historyId":"974b4f92c279c4b003684c34adcda23f","fullName":"tests.AllTests.checkingTheOperationOfTheProductPage","labels":[{"name":"package","value":"tests.AllTests"},{"name":"testClass","value":"tests.AllTests"},{"name":"testMethod","value":"checkingTheOperationOfTheProductPage"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"TestTask"},{"name":"subSuite","value":"tests.AllTests"},{"name":"host","value":"DESKTOP-75777E5"},{"name":"thread","value":"4968@DESKTOP-75777E5.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"owner","value":"Иванов Иван"},{"name":"story","value":"Проверка работы страницы с продуктами пользователя"}],"links":[],"name":"checkingTheOperationOfTheProductPage","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"[Authorization was not successful!] \r\nExpecting actual:\r\n  \"https://www.saucedemo.com/\"\r\nnot to be equal to:\r\n  \"https://www.saucedemo.com/\"\r\n","trace":"java.lang.AssertionError: [Authorization was not successful!] \r\nExpecting actual:\r\n  \"https://www.saucedemo.com/\"\r\nnot to be equal to:\r\n  \"https://www.saucedemo.com/\"\r\n\r\n\tat pages.AuthorizationPage.authorization(AuthorizationPage.java:55)\r\n\tat steps.AuthorizationSteps.logInToTheSystemAs(AuthorizationSteps.java:19)\r\n\tat tests.AllTests.checkingTheOperationOfTheProductPage(AllTests.java:18)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\r\n\tat org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)\r\n\tat org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)\r\n\tat org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)\r\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\r\n\tat java.base/java.lang.Thread.run(Thread.java:842)\r\n"},"stage":"finished","steps":[{"name":"Перейти на страницу авторизации","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[{"name":"expectedTextFields","value":"[Username, Password]"},{"name":"buttonName","value":"LOGIN"}],"start":1716278117046,"stop":1716278117271},{"name":"Авторизоваться в системе пользователем","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"[Authorization was not successful!] \r\nExpecting actual:\r\n  \"https://www.saucedemo.com/\"\r\nnot to be equal to:\r\n  \"https://www.saucedemo.com/\"\r\n","trace":"java.lang.AssertionError: [Authorization was not successful!] \r\nExpecting actual:\r\n  \"https://www.saucedemo.com/\"\r\nnot to be equal to:\r\n  \"https://www.saucedemo.com/\"\r\n\r\n\tat pages.AuthorizationPage.authorization(AuthorizationPage.java:55)\r\n\tat steps.AuthorizationSteps.logInToTheSystemAs(AuthorizationSteps.java:19)\r\n\tat tests.AllTests.checkingTheOperationOfTheProductPage(AllTests.java:18)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\r\n\tat org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)\r\n\tat org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)\r\n\tat org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)\r\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\r\n\tat java.base/java.lang.Thread.run(Thread.java:842)\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[{"name":"login","value":"locked_out_user"},{"name":"password","value":"secret_sauce"}],"start":1716278117271,"stop":1716278117606}],"attachments":[],"parameters":[{"name":"arg1","value":"secret_sauce"},{"name":"arg0","value":"locked_out_user"}],"start":1716278117043,"stop":1716278117607}